#!/usr/bin/env python3
"""Create an original, deterministic PCM source for the compressed codec smoke.

No recordings, music, downloads or third-party samples are used. The generated
stereo signal has a 440 Hz left tone and an 880 Hz right tone at distinct times.
"""

import hashlib
import json
import math
from pathlib import Path
import struct
import sys
import wave

SAMPLE_RATE = 48_000
DURATION = 2


def tone(time, start, end, frequency):
    if not start <= time < end:
        return 0
    envelope = min(1.0, (time - start) / 0.02, (end - time) / 0.02)
    return round(0.4 * 32767 * envelope * math.sin(2 * math.pi * frequency * time))


def generate(destination):
    destination = Path(destination)
    # Never overwrite an existing fixture or arbitrary user-owned output.
    destination.mkdir()
    frames = bytearray()
    for frame in range(SAMPLE_RATE * DURATION):
        time = frame / SAMPLE_RATE
        frames.extend(struct.pack("<hh", tone(time, 0.2, 0.8, 440),
                                  tone(time, 1.2, 1.8, 880)))
    source = destination / "stereo-tones.wav"
    with wave.open(str(source), "wb") as audio:
        audio.setnchannels(2)
        audio.setsampwidth(2)
        audio.setframerate(SAMPLE_RATE)
        audio.writeframes(frames)
    manifest = {
        "kind": "generated-codec-fixture",
        "source": "Original mathematical tones generated by generate_audio.py; no sampled audio",
        "generatorVersion": 1,
        "license": "CC0-1.0 (generated fixture data)",
        "sampleRate": SAMPLE_RATE,
        "frames": SAMPLE_RATE * DURATION,
        "channels": 2,
        "left": {"frequencyHz": 440, "startSeconds": 0.2, "endSeconds": 0.8},
        "right": {"frequencyHz": 880, "startSeconds": 1.2, "endSeconds": 1.8},
        "pcmSHA256": hashlib.sha256(source.read_bytes()).hexdigest(),
        "compressedEncoding": "Apple afconvert AAC, MPEG-4 audio, 128000 bit/s",
        "limitations": "Codec/channel smoke only; not a real guitar or model-quality evaluation",
    }
    (destination / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return source


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate_audio.py NEW_FIXTURE_DIRECTORY")
    print(generate(sys.argv[1]))
